/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: [
        "./pages/**/*.{js,jsx}",
        "./components/**/*.{js,jsx}",
        "./app/**/*.{js,jsx}",
        "./src/**/*.{js,jsx}",
    ],
    theme: {
        container: {
            center: true,
            padding: "2rem",
            screens: {
                "2xl": "1400px",
            },
        },
        extend: {
            colors: {
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                muted: {
                    DEFAULT: "hsl(var(--muted))",
                    foreground: "hsl(var(--muted-foreground))",
                },
                accent: {
                    DEFAULT: "hsl(var(--accent))",
                    foreground: "hsl(var(--accent-foreground))",
                },
                popover: {
                    DEFAULT: "hsl(var(--popover))",
                    foreground: "hsl(var(--popover-foreground))",
                },
                card: {
                    DEFAULT: "hsl(var(--card))",
                    foreground: "hsl(var(--card-foreground))",
                },
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                "accordion-down": {
                    from: { height: 0 },
                    to: { height: "var(--radix-accordion-content-height)" },
                },
                "accordion-up": {
                    from: { height: "var(--radix-accordion-content-height)" },
                    to: { height: 0 },
                },
            },
            animation: {
                "accordion-down": "accordion-down 0.2s ease-out",
                "accordion-up": "accordion-up 0.2s ease-out",
            },
            height: {
                "5%": "5%",
                "10%": "10%",
                "15%": "15%",
                "20%": "20%",
                "21%": "21%",
                "22%": "22%",
                "23%": "23%",
                "24%": "24%",
                "25%": "25%",
                "30%": "30%",
                "35%": "35%",
                "40%": "40%",
                "45%": "45%",
                "50%": "50%",
                "55%": "55%",
                "60%": "60%",
                "65%": "65%",
                "70%": "70%",
                "75%": "75%",
                "80%": "80%",
                "85%": "85%",
                "90%": "90%",
                "95%": "95%",
            },
            width: {
                "5%": "5%",
                "10%": "10%",
                "15%": "15%",
                "20%": "20%",
                "25%": "25%",
                "30%": "30%",
                "35%": "35%",
                "40%": "40%",
                "45%": "45%",
                "50%": "50%",
                "55%": "55%",
                "60%": "60%",
                "65%": "65%",
                "70%": "70%",
                "75%": "75%",
                "80%": "80%",
                "85%": "85%",
                "90%": "90%",
                "95%": "95%",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
